
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:quarkus;DB_CLOSE_ON_EXIT=FALSE

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

hotel-api/mp-rest/url=http://localhost:8080/q   # optional: call your local hotel while testing
taxi-api/mp-rest/url=https://csc-8104-deepal-thakur-deepalthakur-dev.apps.rm1.0a51.p1.openshiftapps.com
flight-api/mp-rest/url=https://csc-8104-matt-rollings-mroll-newc-dev.apps.rm3.7wse.p1.openshiftapps.com

quarkus.rest-client."uk.ac.newcastle.enterprisemiddleware.travel.HotelClient".connect-timeout=5000
quarkus.rest-client."uk.ac.newcastle.enterprisemiddleware.travel.HotelClient".read-timeout=20000

quarkus.rest-client."uk.ac.newcastle.enterprisemiddleware.travel.TaxiClient".connect-timeout=5000
quarkus.rest-client."uk.ac.newcastle.enterprisemiddleware.travel.TaxiClient".read-timeout=20000

quarkus.rest-client."uk.ac.newcastle.enterprisemiddleware.travel.FlightClient".connect-timeout=5000
quarkus.rest-client."uk.ac.newcastle.enterprisemiddleware.travel.FlightClient".read-timeout=20000

quarkus.log.category."uk.ac.newcastle.enterprisemiddleware".level=INFO
